# Generated by Django 2.2 on 2019-07-12 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0002_auto_20190712_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 18, 22, 35, 638949, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('ques_ans', models.TextField()),
                ('ans_date', models.DateTimeField(default=datetime.datetime(2019, 7, 12, 18, 22, 35, 638949, tzinfo=utc))),
                ('slug', models.SlugField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='qanda.Question')),
            ],
        ),
    ]
