# Generated by Django 2.2 on 2019-07-16 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0006_auto_20190713_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upload',
            field=models.FileField(default='def.jpg', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 9, 34, 15, 589042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='asked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 9, 34, 15, 588045, tzinfo=utc)),
        ),
    ]
