# Generated by Django 2.2 on 2019-07-29 16:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qanda', '0008_auto_20190729_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 16, 50, 57, 531731, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='asked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 16, 50, 57, 530706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='upload',
            field=models.ImageField(blank=True, upload_to='folder'),
        ),
    ]
