# Generated by Django 2.2 on 2019-07-30 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qanda', '0024_auto_20190730_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyProfile',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 8, 50, 9, 423764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='asked_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 30, 8, 50, 9, 422765, tzinfo=utc)),
        ),
    ]
